name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: npx run cypress
        uses: cypress-io/github-action@v4.1.0 # use the explicit version number
        with: 
          wait-on: "http://localhost:8888"
          config-file: cypress.config.js
          build: npm run build
          start: netlify dev